<?php

/**
 * @file
 * Adds block for simple and emi calculator.
 */

/**
 * Implements hook_block_info().
 */
function simple_calculator_block_info() {
  $blocks['simple_calculator'] = array(
    'info' => t('Simple Calculator'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function simple_calculator_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'simple_calculator':
      $block['subject'] = t('<none>');
      $block['content'] = drupal_get_form('simple_calculator_form');
  }
  return $block;
}

/**
 * Implements hook_form().
 */
function simple_calculator_form($form, &$form_state) {
    $output = theme('tax_calculator', array('tax_listing' => NULL));
     // Adding js.
    drupal_add_js(drupal_get_path('module', 'simple_calculator') . '/js/tax_calculator.js');
   drupal_add_css(drupal_get_path('module', 'simple_calculator') . '/css/tax.css');
    $form['callback_calculator']['#markup'] = $output;
  
  return $form;
}
  // For block to display available calculators.
  /*$form['calculator_title'] = array(
    '#title' => t('Year End Tax Calculator'),
    '#type' => 'select',
    '#description' => t('Select the calculator type.'),
    '#options' => array(
      'select' => t('--Select--'),
      'simplecalculator' => t('Simple Calculator'),
      'emicalculator' => t('EMI Calculator'),
      'homeloancalculator' => t('Home Loan Calculator'),
      'taxcalculator' => t('Year End Tax Calculator'),   
    ),
    // Ajax callback.
    '#ajax' => array(
      'callback' => 'simple_calculator_callback_form',
      'wrapper' => 'slot-check',
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );
  $calculator_type = !empty($form_state['values']['calculator_type']) ? $form_state['values']['calculator_type'] : '';
  $form['callback_calculator'] = array(
    '#title' => t('<none>'),
    '#prefix' => '<div id="slot-check">',
    '#suffix' => '</div>',
    '#type' => 'markup',
  );
  // Render theme templates.
  if (!empty($form_state['values'])) {
    if ($calculator_type == 'simplecalculator') {
      $output = theme('simple_calculator', array('listing' => NULL));
    }
    if ($calculator_type == 'emicalculator') {
      $output = theme('emi_calculator', array('emi_listing' => NULL));
    }
    if ($calculator_type == 'homeloancalculator') {
      $output = theme('homeloan_calculator', array('homeloan_listing' => NULL));
    }
    if ($calculator_type == 'taxcalculator') {
      
    }*/
   

/**
 * Implements hook_theme().
 */
function simple_calculator_theme() {
  // For simple , emi calculators.
  $themes = array(
    'simple_calculator' => array(
      'template' => 'templates/simplecalculator',
      'arguments' => array('listing' => NULL),
    ),
    'emi_calculator' => array(
      'template' => 'templates/emicalculator',
      'arguments' => array('emi_listing' => NULL),
    ),
    'homeloan_calculator' => array(
      'template' => 'templates/homeloan',
      'arguments' => array('homeloan_listing' => NULL),
    ),
    'tax_calculator' => array(
      'template' => 'templates/taxcalculator',
      'arguments' => array('tax_listing' => NULL),
    ),
  );
  return $themes;
}

/**
 * Callback for calculator dropdown.
 */
function simple_calculator_callback_form($form, &$form_state) {
  return $form['callback_calculator'];
}
